# Generated by Django 4.2.4 on 2023-08-08 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='persons',
            field=models.PositiveIntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco'), (6, 'Seis'), (7, 'Siete'), (8, 'Ocho'), (9, 'Nueve'), (10, 'Diez')]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='taste',
            field=models.PositiveIntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco'), (6, 'Seis'), (7, 'Siete'), (8, 'Ocho'), (9, 'Nueve'), (10, 'Diez')]),
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('enlace', models.URLField()),
                ('orden', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.curso')),
            ],
        ),
    ]
