# Generated by Django 4.2.4 on 2023-08-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_curso_lecciones_leccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='lecciones',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='cursos.leccion'),
        ),
    ]
