# Generated by Django 4.2.4 on 2023-08-09 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_curso_lecciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='lecciones',
        ),
    ]
