# Generated by Django 4.2.4 on 2023-08-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_remove_curso_taste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='persons',
            field=models.PositiveIntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco'), (6, 'Seis'), (7, 'Siete'), (8, 'Ocho'), (9, 'Nueve'), (10, 'Diez')], default=0),
        ),
    ]
